// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdvfprzywxvoiptcuszu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkdmZwcnp5d3h2b2lwdGN1c3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjQwNzQsImV4cCI6MjA2OTEwMDA3NH0.7HHrLdIgpHF-UYVSihiVwcIaVunMuhpnk-7TNfUUaNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);