// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eispefpykpnrmcqmpiag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpc3BlZnB5a3Bucm1jcW1waWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzAzNDksImV4cCI6MjA2NTkwNjM0OX0.oajU7Mt9hA3qu4K7FzclWQKTZ9Ngcm0RzZId4gQs5R4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);